### ISSUE TITLE
Unexpected token while loading tasks

### ISSUE THREAD

**Issue by rafegoldberg** [rickekelschot/grunt-json-to-sass#5]
When I run the `json_to_sass` task with the this config:

```
json_to_sass: {
    files: [{
      src: [
        'shared/test.json'
        ],
      dest: '_example.scss'
      }]
    }
```

I get the following error:

 ```
Loading "json_to_sass.js" tasks...ERROR
>> SyntaxError: Unexpected token .
```

Any ideas what might be causing this?

**Comment by rafegoldberg** [comment]
If it's any help, here's the full trace from Grunt's verbose output:

```
Registering "grunt-json-to-sass" local Npm module tasks.
Reading ~/Desktop/env/node_modules/grunt-json-to-sass/package.json...OK
Parsing ~/Desktop/env/node_modules/grunt-json-to-sass/package.json...OK
Loading "json_to_sass.js" tasks...ERROR
>> ~/Desktop/env/node_modules/grunt-json-to-sass/tasks/json_to_sass.js:62
>>             .replace(/\]/g, ')');
>>             ^
>> SyntaxError: Unexpected token .
>>   at Object.exports.runInThisContext (vm.js:76:16)
>>   at Module._compile (module.js:542:28)
>>   at Object.Module._extensions..js (module.js:579:10)
>>   at Module.load (~/Desktop/env/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>   at tryModuleLoad (module.js:446:12)
>>   at Function.Module._load (module.js:438:3)
>>   at Module.require (module.js:497:17)
>>   at require (internal/module.js:20:19)
>>   at loadTask (~/Desktop/env/node_modules/grunt/lib/grunt/task.js:316:10)
>>   at ~/Desktop/env/node_modules/grunt/lib/grunt/task.js:354:7
>>   at Array.forEach (native)
>>   at loadTasks (~/Desktop/env/node_modules/grunt/lib/grunt/task.js:353:11)
>>   at Task.task.loadNpmTasks (~/Desktop/env/node_modules/grunt/lib/grunt/task.js:401:5)
>>   at Array.forEach (native)
>>   at module.exports (~/Desktop/env/node_modules/load-grunt-config/node_modules/load-grunt-tasks/index.js:25:29)
>>   at module.exports (~/Desktop/env/node_modules/load-grunt-config/index.js:67:32)
>>   at Object.module.exports (~/Desktop/env/Gruntfile.js:8:31)
>>   at loadTask (~/Desktop/env/node_modules/grunt/lib/grunt/task.js:318:10)
>>   at Task.task.init (~/Desktop/env/node_modules/grunt/lib/grunt/task.js:437:5)
>>   at Object.grunt.tasks (~/Desktop/env/node_modules/grunt/lib/grunt.js:111:8)
>>   at Object.module.exports [as cli] (~/Desktop/env/node_modules/grunt/lib/grunt/cli.js:27:9)
>>   at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:44:20)
>>   at Module._compile (module.js:570:32)
>>   at Object.Module._extensions..js (module.js:579:10)
>>   at Module.load (module.js:487:32)
>>   at tryModuleLoad (module.js:446:12)
>>   at Function.Module._load (module.js:438:3)
>>   at Module.runMain (module.js:604:10)
>>   at run (bootstrap_node.js:394:7)
>>   at startup (bootstrap_node.js:149:9)
>>   at bootstrap_node.js:509:3
```

**Comment by rickekelschot** [comment]
It is fixed in version 0.0.5. Thanks for your effort.

**Comment by rafegoldberg** [comment]
much appreciated my man; will pull in your changes and test the fix later today!

**Comment by JavRok** [comment]
Thanks for the fix! Can you now update the npm with latest version? :)

**Comment by gregorybolkenstijn** [comment]
Please update NPM as stated above, thanks
